language: cpp
dist: trusty
sudo: required

git:
  submodules: true
  depth: 3

matrix:
  include:
  - os: osx
    compiler: clang++
    env: AudioPlugin HoaLibraryVR
    script:
    - cd NativeCode
    - mkdir build && cd build
    - cmake -G Xcode -DCMAKE_BUILD_TYPE=Release ..
    - xcodebuild -configuration Release -target install

notifications:
  email: true
